### PR TITLE
fix ScrollToEnd behavior

### PR DESCRIPTION
**Pull request by v0vc**
fix incorrect scroll position

### CODE REVIEW

**Comment by whereswaldon** [comment]
Could you please elaborate on this change? I do not understand the problem that this solves. With your changes, opening one of the chat does not keep the bottom, newest messages in view. Could you describe what you expected to happen, and what was happening instead?

**Comment by v0vc** [comment]
First of all thank you for the best gio example, its a really brilliant work!
In my case, i need to scroll list in from up to bottom, chat list in your code have oldest messages in the top of control, but in my case i wont to have oldest items at the bottom of control. 
None of the combinations of options ScrollToEnd/Stickiness gave me the expected result. In case ScrollToEnd false/Stickiness before - list loaded full of elements, no async "magic" where scrolling. In case ScrollToEnd false/Stickiness after - scroll position at the start is incorrent, i think it's a bug (but it works ok in your chat case).  So you can easy reproduce this behavior, just set ScrollToEnd false and config.BufferSize more than config.LoadSize (i use 100/30).
I don't insist, just those who want to use your control with mirror scrolling (from up to bottom instead of your case from bottom to up) will face the same problem as me.
Anyway thank you for the great job, it made me look differently on gio, i think its really cool framework, use it with pride in my ui part of [solution](https://github.com/v0vc/go-music-grpc/tree/main/gio-gui)

**Comment by JackMordaunt** [comment]
Hi @v0vc, would you be so kind as to record a video of the before/after showing the behaviour that you want?

**Comment by v0vc** [comment]
https://github.com/gioverse/chat/assets/9407549/329f20a5-1459-4483-a1d6-b18b0f3f2b96

**Comment by JackMordaunt** [comment]
@v0vc That format doesn't want to display correctly! 

image

**Comment by v0vc** [comment]
image
Chrome show ok...
same file in [archive](https://temp.sh/ZiFAm/Video_2023-07-31_100436.zip)

**Comment by JackMordaunt** [comment]
So, are you wanting the list to start from the oldest message? Eg not have it stuck to the bottom, nor need to scroll the beginning?

**Comment by v0vc** [comment]
image
in my case i want to start from newest "messages" and scroll down with async loader to the oldest items, mirror case from your variant

**Review by whereswaldon — APPROVED** [review]
Now that I understand what you're going for, I'm happy to accept this change. I've pushed it and a follow-on commit, though they may take some time to show up on GitHub. https://git.sr.ht/~gioverse/chat/commit/962500503098240bc9d34b6781eeb5b312ef7d1c

**Comment by v0vc** [comment]
Thanks!
Can i create some issues here or it wood be better in main gio [repository](https://github.com/gioui/gio)?
It's about this control, but i think it's a framework behavior..

**Comment by whereswaldon** [comment]
You can create issues about this repo [here](https://todo.sr.ht/~gioverse/chat)

**Comment by whereswaldon** [comment]
@v0vc Could you actually sign-off your commit to indicate acceptance of the [DCO](https://developercertificate.org/) and license terms? We use the same contribution guidelines as [Gio](https://gioui.org/doc/contribute#style) on this repo. Without a signed-off commit, I can't finalize this change (and I can't do it for you, since it's a legal thing).

Just force-push a signed-off version of the commit to this branch.

**Comment by v0vc** [comment]
@whereswaldon done, just force-pushed with --signoff

**Comment by JackMordaunt** [comment]
Thanks @v0vc

**Pull request merged**
